repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=2048]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
  - repo: https://gitlab.com/jvenom/elixir-pre-commit-hooks
    rev: v1.1.0
    hooks:
      - id: mix-format
      - id: mix-test
        args: []
